# Change these first
owner: 0xflotus # Your GitHub username
repo: dinos-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Dinos Website
    url: https://dinos.js.org
  - name: Dinos Monitoring itself
    url: https://0xflotus.github.io/dinos-monitor/
  - name: personal Github Page
    url: https://0xflotus.github.io

assignees:
  - 0xflotus

status-website:
  baseUrl: /dinos-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dinos
  introTitle: An experimental DNS Client
  introMessage: This is the status site for [dinos.js.org](https://dinos.js.org)<br />‼️⚠️ THIS PROJECT IS CURRENTLY NOT MAINTAINED!

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "*/5 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
