# Change these first
owner: 0xflotus # Your GitHub username
repo: dinos-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Dinos
    url: https://dinos.js.org
  - name: Wikipedia
    url: https://de.wikipedia.org

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dinos
  introTitle: An experimental DNS Client
  introMessage: Welcome
    - title: Status
      href: /dinos-monitor
    - title: GitHub
      href: https://github.com/0xflotus/dinos-monitor
