# Change these first
owner: 0xflotus # Your GitHub username
repo: dinos-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Dinos Website
    url: https://dinos.js.org

assignees:
  - 0xflotus

status-website:
  baseUrl: /dinos-monitor/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dinos
  introTitle: An experimental DNS Client
  introMessage: This is the status site for <a href="dinos.js.org">dinos.js.org</a>
